---
title: "design"
format: html
editor: visual
---

## Step 1: Sketching the Design

Before coding, create a one‑page design document and have it approved by the instructor or TA.

<<<<<<< Updated upstream
## **Sketching the Design**

-Tables for 3 different fleet size (50, 75, 100)

-For each fleet size we will give a table with one row per station 

-   Each table can include (Station ID, Recommended starting bike)
<<<<<<< HEAD
-   
-   
=======

<!-- -->

-   aaa
=======
1.  Define the final output: What should the manager receive (e.g., a table of recommended bikes per station, an expected‑usage plot)

    The manager should receive

2.  Outline the high‑level steps, from data input to final results. Continue breaking down these steps until each piece is simple enough to be contained in its own function.

3.  List your functions. For each function include:

    -   Function name
    -   Inputs (with data types)
    -   Outputs (with formats)
    -   Short description of its purpose

4.  Draw a function dependency diagram showing the dependence of functions on each other.

5.  Refine by considering where you could minimize redundancy or update the inputs/outputs to improve your design.
>>>>>>> Stashed changes
>>>>>>> ec9aebd205e01b95b58613c73f1d14c1e7065fd9
